import {
  Archive,
  CalendarPlus,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock3,
  CornerDownRight,
  Download,
  Mail as MailIcon,
  Paperclip,
  Printer,
  ShieldAlert,
  ShieldCheck,
  Send,
  Star,
  Trash2,
} from 'lucide-react'
import { useEffect, useState } from 'react'
import { MailBodyFrame } from './MailBodyFrame'
import { buildThread, snoozeAt, snoozeOptions } from '../lib/mail'
import { getLocalAttachment, getRemoteAttachment } from '../services/attachments'
import { foldersApi } from '../services/folders'
import { useSettings } from '../services/settings'
import { isRemoteMail } from '../services/remote-mail'
import type { Mail, ReaderThreadItem, SecurityVerdicts } from '../types'

type ReaderProps = {
  mail: Mail
  thread?: ReaderThreadItem[]
  threadStatus?: 'loading' | 'ready' | 'error' | 'demo'
  onRetryThread?: () => void
  onReply: (item?: ReaderThreadItem) => void
  onReplyAll: (item?: ReaderThreadItem) => void
  onForward: () => void
  onToggleStar: () => void
  onToggleRead: () => void
  onBack?: () => void
  onArchive?: () => void
  onDelete?: () => void
  onMove?: (folder: string) => void
  onSnooze?: (until: string) => void
  onSpam?: () => void
  onPrint?: () => void
  onSave?: () => void
  onAddToCalendar?: () => void
  onPrevious?: () => void
  onNext?: () => void
  canPrevious?: boolean
  canNext?: boolean
}

const moveChoices: string[] = ['Inbox', 'Archive', 'Snoozed', 'Spam', 'Trash']

const verdictLabel = (verdict: SecurityVerdicts['spf']) =>
  verdict === 'pass'
    ? 'pass'
    : ['fail', 'softfail'].includes(verdict)
      ? 'failed'
      : verdict === 'temperror' || verdict === 'permerror'
        ? 'error'
        : verdict === 'none'
          ? 'not checked'
          : verdict

const verdictClass = (verdict: SecurityVerdicts['spf']) =>
  verdict === 'pass'
    ? 'ok'
    : ['fail', 'softfail'].includes(verdict)
      ? 'bad'
      : verdict === 'temperror' || verdict === 'permerror'
        ? 'bad'
        : ''

const SecurityChip = ({
  method,
  verdict,
}: {
  method: string
  verdict: SecurityVerdicts['spf']
}) => (
  <span className={verdictClass(verdict)}>
    {method} {verdictLabel(verdict)}
  </span>
)

const renderSecurity = (security: SecurityVerdicts | undefined) => {
  if (!security) return null
  const chips = [
    <SecurityChip key="spf" method="SPF" verdict={security.spf} />,
    <SecurityChip key="dkim" method="DKIM" verdict={security.dkim} />,
    <SecurityChip key="dmarc" method="DMARC" verdict={security.dmarc} />,
  ]
  if (security.spam)
    chips.push(
      <span key="spam" className="bad">
        Spam ({security.score.toFixed(1)} rating)
      </span>,
    )
  else if (security.score > 0)
    chips.push(<span key="score">Score {security.score.toFixed(1)}</span>)
  return chips
}

const downloadBlob = (blob: Blob, name: string) => {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = name
  link.click()
  URL.revokeObjectURL(url)
}

const asciiEscaped = (value: string) => value.replace(/[\\()\r\n]/g, ' ')

const makePdf = (mail: Mail, name: string): Blob => {
  const text = `Attachment: ${name}\nSource: ${mail.subject}\nGenerated by the CS Mail preview.`
  const objects: string[] = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ]
  const stream = `BT /F1 12 Tf 72 720 Td (${asciiEscaped(text)}) Tj ET`
  const streamLength = new TextEncoder().encode(stream).byteLength
  let pdf = '%PDF-1.4\n'
  const offsets: number[] = [0]
  const lines = [
    `1 0 obj\n${objects[0]}\nendobj`,
    `2 0 obj\n${objects[1]}\nendobj`,
    `3 0 obj\n${objects[2]}\nendobj`,
    `4 0 obj\n<< /Length ${streamLength} >>\nstream\n${stream}\nendstream\nendobj`,
    `5 0 obj\n${objects[3]}\nendobj`,
  ]
  for (const line of lines) {
    offsets.push(new TextEncoder().encode(pdf).byteLength)
    pdf += `${line}\n`
  }
  offsets.push(new TextEncoder().encode(pdf).byteLength)
  pdf += `xref\n0 ${offsets.length}\n0000000000 65535 f \n`
  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${offsets[offsets.length - 1]}\n%%EOF`
  return new Blob([pdf], { type: 'application/pdf' })
}

const saveEmailAsFile = (mail: Mail, thread: { sender: string; email: string; copy: string }[]) => {
  const recipients = mail.to ?? []
  const body = thread.map((item) => `${item.sender} <${item.email}>\n${item.copy}`).join('\n\n')
  const ccLine = mail.cc && mail.cc.length > 0 ? [`Cc: ${mail.cc.join(', ')}`] : []
  const parts = [
    `From: ${mail.sender} <${mail.email}>`,
    `To: ${recipients.join(', ')}`,
    ...ccLine,
    `Subject: ${mail.subject}`,
    `Date: ${mail.time}`,
    'MIME-Version: 1.0',
    'Content-Type: text/plain; charset=utf-8',
    '',
    body,
  ]
  const blob = new Blob([parts.join('\r\n')], { type: 'message/rfc822' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${mail.subject.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '') || 'message'}.eml`
  link.click()
  URL.revokeObjectURL(url)
}

export function Reader({
  mail,
  thread: friendThread,
  threadStatus = 'demo',
  onRetryThread,
  onReply,
  onReplyAll,
  onForward,
  onToggleStar,
  onToggleRead,
  onBack,
  onArchive,
  onDelete,
  onMove,
  onSnooze,
  onSpam,
  onPrint,
  onSave,
  onAddToCalendar,
  onPrevious,
  onNext,
  canPrevious,
  canNext,
}: ReaderProps) {
  const [openMessage, setOpenMessage] = useState(-2)
  const recipientDisplay = mail.to && mail.to.length > 0 ? mail.to.join(', ') : 'Recipient unavailable'
  const [moveOpen, setMoveOpen] = useState(false)
  const [snoozeOpen, setSnoozeOpen] = useState(false)
  const [detailsOpen, setDetailsOpen] = useState(false)
  // Consent is keyed to the current message ID rather than a bare boolean, so
  // switching messages synchronously blocks remote images again.
  const [remoteImagesForMessage, setRemoteImagesForMessage] = useState<string | null>(null)
  const { conversations, safeLinks } = useSettings()
  const dispatchAction = (action: 'archive' | 'trash') => {
    if (action === 'archive') onArchive?.()
    else onDelete?.()
  }
  // A live mailbox must never display a fabricated conversation while its
  // provider request is pending or has failed.
  const live = isRemoteMail()
  const thread = live ? (friendThread ?? []) : (friendThread ?? buildThread(mail))
  const conversation = conversations ? thread : thread.slice(0, 1)
  const openIndex = openMessage === -2 || openMessage >= conversation.length
    ? conversation.length - 1
    : openMessage
  const currentFolder = mail.folder || 'Inbox'
  const moveChoicesAll = [
    ...moveChoices,
    ...foldersApi.list().map((customFolder) => customFolder.name),
  ].filter((folder) => folder !== currentFolder)

  useEffect(() => {
    if (!onMove && !onSnooze) return
    const close = () => {
      setMoveOpen(false)
      setSnoozeOpen(false)
    }
    const esc = (event: KeyboardEvent) => {
      if (event.key === 'Escape') close()
    }
    window.addEventListener('click', close)
    window.addEventListener('keydown', esc)
    return () => {
      window.removeEventListener('click', close)
      window.removeEventListener('keydown', esc)
    }
  }, [onMove, onSnooze])

  const downloadAttachment = async () => {
    const name = mail.attachmentName ?? 'attachment'
    const local = await getLocalAttachment(name)
    if (local) {
      downloadBlob(local, name)
      return
    }
    if (/\.pdf$/i.test(name)) {
      downloadBlob(makePdf(mail, name), name)
      return
    }
    downloadBlob(
      new Blob(
        [
          `Attachment: ${name}\nSource message: ${mail.subject}\nThis demo message carries a downloaded attachment.\n`,
        ],
        { type: 'text/plain' },
      ),
      name,
    )
  }

  const downloadRemoteAttachment = async (blobId: string, name: string) => {
    const blob = await getRemoteAttachment(blobId)
    if (blob) downloadBlob(blob, name)
  }

  const isRealThreadItem = (item: (typeof thread)[number] | undefined): item is ReaderThreadItem =>
    Boolean(item && 'threadId' in item && item.threadId)

  const openItem = conversation[Math.max(0, openIndex)]
  const security = isRealThreadItem(openItem) ? openItem.security : undefined
  const allowRemoteImages = remoteImagesForMessage === mail.id
  const hasRemoteImages = conversation.some(
    (item) =>
      isRealThreadItem(item) &&
      Boolean(item.bodyHtml && /<img\b[^>]*\bsrc\s*=\s*["']https?:\/\//i.test(item.bodyHtml)),
  )

  const renderCopy = (item: (typeof thread)[number]) => {
    if (isRealThreadItem(item)) {
      if (item.bodyHtml)
        return (
          <MailBodyFrame
            html={item.bodyHtml}
            subject={item.subject}
            allowRemoteImages={allowRemoteImages}
          />
        )
      return item.clearBody
        .split(/\n\n+/)
        .filter(Boolean)
        .map((paragraph) => <p key={paragraph.slice(0, 24)}>{paragraph}</p>)
    }
    return (
      <>
        <p>Hi Alex,</p>
        <p>{item.copy}</p>
        <p>Could you take a look and share your feedback?</p>
        <p>
          Thanks,
          <br />
          {item.sender}
        </p>
      </>
    )
  }

  return (
    <aside className="reader" aria-label="Message">
      <div className="reader-toolbar">
        <button className="icon-button reader-back" aria-label="Back" onClick={onBack}>
          <ChevronLeft size={17} />
          <span className="reader-back__label">Back</span>
        </button>
        <button
          className="icon-button"
          aria-label="Previous message"
          disabled={!canPrevious}
          onClick={onPrevious}
        >
          <ChevronLeft size={17} />
        </button>
        <button
          className="icon-button"
          aria-label="Next message"
          disabled={!canNext}
          onClick={onNext}
        >
          <ChevronRight size={17} />
        </button>
        <span className="reader-toolbar__sep" />
        <button
          className="icon-button"
          aria-label="Archive"
          onClick={() => dispatchAction('archive')}
        >
          <Archive size={17} />
        </button>
        <button className="icon-button" aria-label="Delete" onClick={() => dispatchAction('trash')}>
          <Trash2 size={17} />
        </button>
        <button
          className="icon-button"
          aria-label={mail.unread ? 'Mark as read' : 'Mark as unread'}
          aria-pressed={mail.unread}
          onClick={onToggleRead}
        >
          <MailIcon size={17} />
        </button>
        <button
          className="icon-button"
          aria-label={mail.starred ? 'Unstar' : 'Star'}
          aria-pressed={mail.starred}
          onClick={onToggleStar}
        >
          <Star size={17} fill={mail.starred ? 'currentColor' : 'none'} />
        </button>
        <button
          className="icon-button"
          aria-label="Add to calendar"
          onClick={onAddToCalendar}
          disabled={!onAddToCalendar}
          title="Add to calendar"
        >
          <CalendarPlus size={17} />
        </button>
        <span className="toolbar-spacer" />
        <div className="toolbar-pop">
          <button
            className="icon-button"
            aria-label="Move to folder"
            aria-expanded={moveOpen}
            onClick={(event) => {
              event.stopPropagation()
              setMoveOpen((value) => !value)
            }}
            disabled={!onMove}
          >
            <CornerDownRight size={17} />
          </button>
          {moveOpen && (
            <div
              className="toolbar-menu toolbar-menu--right"
              role="menu"
              aria-label="Move to folder"
            >
              {moveChoicesAll.map((folder) => (
                <button
                  type="button"
                  role="menuitem"
                  key={folder}
                  onClick={(event) => {
                    event.stopPropagation()
                    setMoveOpen(false)
                    onMove?.(folder)
                  }}
                >
                  {folder}
                </button>
              ))}
            </div>
          )}
        </div>
        <div className="toolbar-pop">
          <button
            className="icon-button"
            aria-label="Snooze"
            aria-expanded={snoozeOpen}
            onClick={(event) => {
              event.stopPropagation()
              setSnoozeOpen((value) => !value)
            }}
            disabled={!onSnooze}
          >
            <Clock3 size={17} />
          </button>
          {snoozeOpen && (
            <div className="toolbar-menu toolbar-menu--right" role="menu" aria-label="Snooze until">
              {snoozeOptions.map((option) => (
                <button
                  type="button"
                  role="menuitem"
                  key={option.id}
                  onClick={(event) => {
                    event.stopPropagation()
                    setSnoozeOpen(false)
                    onSnooze?.(snoozeAt(option.id))
                  }}
                >
                  {option.label}
                </button>
              ))}
            </div>
          )}
        </div>
        <button className="icon-button" aria-label="Print" onClick={onPrint} disabled={live && threadStatus !== 'ready'}>
          <Printer size={17} />
        </button>
        <button
          className="icon-button"
          aria-label="Save email as file"
          disabled={live && (threadStatus !== 'ready' || thread.length === 0)}
          onClick={() => {
            if (onSave) onSave()
            else saveEmailAsFile(mail, thread)
          }}
        >
          <Download size={17} />
        </button>
        <button className="icon-button" aria-label="Report spam" onClick={onSpam}>
          <ShieldAlert size={17} />
        </button>
      </div>
      <div className="reader-content">
        <p className="eyebrow">{mail.label} · conversation</p>
        <h2>{mail.subject}</h2>
        <div className="reader-details">
          <span className={`avatar avatar--${mail.color}`}>{mail.initials}</span>
          <span>
            <strong>{mail.sender}</strong>
            <small>
              &lt;{mail.email}&gt; to {recipientDisplay}
            </small>
          </span>
          <time>{mail.time}</time>
          <button
            className="icon-button reader-details__toggle"
            aria-label={detailsOpen ? 'Hide message details' : 'Show message details'}
            aria-expanded={detailsOpen}
            onClick={() => setDetailsOpen((value) => !value)}
          >
            <ChevronDown size={14} />
          </button>
        </div>
        {detailsOpen && (
          <div className="reader-envelope">
            <dl className="reader-envelope__rows">
              <div>
                <dt>From</dt>
                <dd>
                  {mail.sender} &lt;{mail.email}&gt;
                </dd>
              </div>
              <div>
                <dt>To</dt>
                <dd>{recipientDisplay}</dd>
              </div>
              {mail.cc && mail.cc.length > 0 && (
                <div>
                  <dt>Cc</dt>
                  <dd>{mail.cc.join(', ')}</dd>
                </div>
              )}
              <div>
                <dt>Date</dt>
                <dd>{mail.time}</dd>
              </div>
              <div>
                <dt>Subject</dt>
                <dd>{mail.subject}</dd>
              </div>
            </dl>
            <div className="reader-envelope__security">
              <ShieldCheck size={14} />
              {renderSecurity(security) ?? <span>Not verified by this server</span>}
            </div>
          </div>
        )}
        {hasRemoteImages && !allowRemoteImages && (
          <div className="reader-links-note reader-remote-images">
            <ShieldAlert size={14} />
            <span>Remote images are blocked to prevent tracking pixels.</span>
            <button
              type="button"
              className="text-button"
              onClick={() => setRemoteImagesForMessage(mail.id)}
            >
              Load images for this message
            </button>
          </div>
        )}
        {live && threadStatus === 'loading' && (
          <div className="list-state" role="status">Loading the message from your mailbox…</div>
        )}
        {live && threadStatus === 'error' && (
          <div className="list-state" role="alert">
            <strong>Could not load this conversation</strong>
            <span>Your message is still in the inbox. Try loading it again.</span>
            <button type="button" className="secondary-button" onClick={onRetryThread}>Retry</button>
          </div>
        )}
        {live && threadStatus === 'ready' && thread.length === 0 && (
          <div className="list-state" role="status">No messages were returned for this conversation.</div>
        )}
        <div className="thread-stack">
          {conversation.map((item, index) => (
            <article
              className={`thread-message ${openIndex === index ? 'thread-message--open' : ''}`}
              key={`${'id' in item && item.id ? item.id : item.sender}-${index}`}
            >
              <header>
                <span className={`avatar avatar--${item.color}`}>{item.initials}</span>
                <span>
                  <strong>{item.sender}</strong>
                  <small>
                    {item.email} · to {isRealThreadItem(item) && item.to?.length ? item.to.join(', ') : recipientDisplay}
                  </small>
                </span>
                <time>{item.time}</time>
                <button
                  className="icon-button"
                  aria-label={`${openIndex === index ? 'Collapse' : 'Expand'} message`}
                  onClick={() => setOpenMessage((current) => (current === index ? -1 : index))}
                >
                  <ChevronDown size={15} />
                </button>
              </header>
              {openIndex === index && <div className="reader-copy">{renderCopy(item)}</div>}
              {openIndex === index &&
                isRealThreadItem(item) &&
                item.attachments &&
                item.attachments.length > 0 && (
                  <div className="attachment-list">
                    {item.attachments.map((file) => (
                      <div className="attachment" key={file.blobId}>
                        <Paperclip size={16} />
                        <span>
                          <strong>{file.name}</strong>
                          <small>{file.type}</small>
                        </span>
                        <button
                          className="secondary-button"
                          onClick={() => void downloadRemoteAttachment(file.blobId, file.name)}
                        >
                          <Send size={15} />
                          Download
                        </button>
                      </div>
                    ))}
                  </div>
                )}
            </article>
          ))}
        </div>
        {!live && mail.attachment && (
          <div className="attachment">
            <Paperclip size={16} />
            <span>
              <strong>{mail.attachmentName ?? 'attachment'}</strong>
              <small>Scanned and safe</small>
            </span>
            <button className="secondary-button" onClick={downloadAttachment}>
              <Send size={15} />
              Download
            </button>
          </div>
        )}
        <div className="reader-actions">
          <button
            className="primary-button"
            disabled={live && (threadStatus !== 'ready' || !isRealThreadItem(openItem))}
            onClick={() => onReply(isRealThreadItem(openItem) ? openItem : undefined)}
          >
            <MailIcon size={15} />
            Reply
          </button>
          <button
            className="secondary-button"
            disabled={live && (threadStatus !== 'ready' || !isRealThreadItem(openItem))}
            onClick={() => onReplyAll(isRealThreadItem(openItem) ? openItem : undefined)}
          >
            <MailIcon size={15} />
            Reply all
          </button>
          <button className="secondary-button" onClick={onForward}>
            <Send size={15} />
            Forward
          </button>
        </div>
        {safeLinks && (
          <div className="reader-links-note">
            <ShieldCheck size={14} />
            <span>
              Safe links are on — CS Mail checks the links in this message before they open.
            </span>
          </div>
        )}
      </div>
    </aside>
  )
}
