import { Archive, CalendarPlus, ChevronDown, ChevronLeft, ChevronRight, Clock3, CornerDownRight, Download, Mail as MailIcon, Paperclip, Printer, ShieldAlert, ShieldCheck, Send, Star, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { buildThread, snoozeAt, snoozeOptions } from '../lib/mail'
import { getLocalAttachment, getRemoteAttachmentUrl } from '../services/attachments'
import { foldersApi } from '../services/folders'
import { useSettings } from '../services/settings'
import type { Mail } from '../types'

type ReaderProps = {
  mail: Mail
  onReply: () => void
  onReplyAll: () => void
  onForward: () => void
  onToggleStar: () => void
  onToggleRead: () => void
  onBack?: () => void
  onArchive?: () => void
  onDelete?: () => void
  onMove?: (folder: string) => void
  onSnooze?: (until: string) => void
  onSpam?: () => void
  onPrint?: () => void
  onSave?: () => void
  onAddToCalendar?: () => void
  onPrevious?: () => void
  onNext?: () => void
  canPrevious?: boolean
  canNext?: boolean
}

const moveChoices: string[] = ['Inbox', 'Archive', 'Snoozed', 'Spam', 'Trash']

const downloadBlob = (blob: Blob, name: string) => {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = name
  link.click()
  URL.revokeObjectURL(url)
}

const asciiEscaped = (value: string) => value.replace(/[\\()\r\n]/g, ' ')

const makePdf = (mail: Mail, name: string): Blob => {
  const text = `Attachment: ${name}\nSource: ${mail.subject}\nGenerated by the Harbor Mail preview.`
  const objects: string[] = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ]
  const stream = `BT /F1 12 Tf 72 720 Td (${asciiEscaped(text)}) Tj ET`
  const streamLength = new TextEncoder().encode(stream).byteLength
  let pdf = '%PDF-1.4\n'
  const offsets: number[] = [0]
  const lines = [
    `1 0 obj\n${objects[0]}\nendobj`,
    `2 0 obj\n${objects[1]}\nendobj`,
    `3 0 obj\n${objects[2]}\nendobj`,
    `4 0 obj\n<< /Length ${streamLength} >>\nstream\n${stream}\nendstream\nendobj`,
    `5 0 obj\n${objects[3]}\nendobj`,
  ]
  for (const line of lines) {
    offsets.push(new TextEncoder().encode(pdf).byteLength)
    pdf += `${line}\n`
  }
  offsets.push(new TextEncoder().encode(pdf).byteLength)
  pdf += `xref\n0 ${offsets.length}\n0000000000 65535 f \n`
  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${offsets[offsets.length - 1]}\n%%EOF`
  return new Blob([pdf], { type: 'application/pdf' })
}

const saveEmailAsFile = (mail: Mail, thread: { sender: string; email: string; copy: string }[]) => {
  const recipients = mail.to && mail.to.length > 0 ? mail.to : ['alex@harbor.co']
  const body = thread.map(item => `${item.sender} <${item.email}>\n${item.copy}`).join('\n\n')
  const ccLine = mail.cc && mail.cc.length > 0 ? [`Cc: ${mail.cc.join(', ')}`] : []
  const parts = [
    `From: ${mail.sender} <${mail.email}>`,
    `To: ${recipients.join(', ')}`,
    ...ccLine,
    `Subject: ${mail.subject}`,
    `Date: ${mail.time}`,
    'MIME-Version: 1.0',
    'Content-Type: text/plain; charset=utf-8',
    '',
    body,
  ]
  const blob = new Blob([parts.join('\r\n')], { type: 'message/rfc822' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${mail.subject.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '') || 'message'}.eml`
  link.click()
  URL.revokeObjectURL(url)
}

export function Reader({ mail, onReply, onReplyAll, onForward, onToggleStar, onToggleRead, onBack, onArchive, onDelete, onMove, onSnooze, onSpam, onPrint, onSave, onAddToCalendar, onPrevious, onNext, canPrevious, canNext }: ReaderProps) {
  const [openMessage, setOpenMessage] = useState(2)
  const recipientDisplay = mail.to && mail.to.length > 0 ? mail.to.join(', ') : 'Alex Morgan'
  const [moveOpen, setMoveOpen] = useState(false)
  const [snoozeOpen, setSnoozeOpen] = useState(false)
  const { conversations, safeLinks } = useSettings()
  const dispatchAction = (action: 'archive' | 'trash') => { if (action === 'archive') onArchive?.(); else onDelete?.() }
  const thread = buildThread(mail)
  const conversation = conversations ? thread : [thread[0]]
  const currentFolder = mail.folder || 'Inbox'
  const moveChoicesAll = [...moveChoices, ...foldersApi.list().map(customFolder => customFolder.name)].filter(folder => folder !== currentFolder)

  useEffect(() => {
    if (!onMove && !onSnooze) return
    const close = () => { setMoveOpen(false); setSnoozeOpen(false) }
    const esc = (event: KeyboardEvent) => { if (event.key === 'Escape') close() }
    window.addEventListener('click', close)
    window.addEventListener('keydown', esc)
    return () => {
      window.removeEventListener('click', close)
      window.removeEventListener('keydown', esc)
    }
  }, [onMove, onSnooze])

  const downloadAttachment = async () => {
    const name = mail.attachmentName ?? 'attachment'
    const remoteUrl = getRemoteAttachmentUrl(name)
    if (remoteUrl) {
      try {
        const response = await fetch(remoteUrl, { credentials: 'include' })
        if (response.ok) { downloadBlob(await response.blob(), name); return }
      } catch { /* fall through to local or generated download */ }
    }
    const local = await getLocalAttachment(name)
    if (local) { downloadBlob(local, name); return }
    if (/\.pdf$/i.test(name)) { downloadBlob(makePdf(mail, name), name); return }
    downloadBlob(new Blob([`Attachment: ${name}\nSource message: ${mail.subject}\nThis demo message carries a downloaded attachment.\n`], { type: 'text/plain' }), name)
  }

  return (
    <aside className="reader" aria-label="Message">
      <div className="reader-toolbar">
        <button className="icon-button reader-back" aria-label="Back" onClick={onBack}><ChevronLeft size={17} /><span className="reader-back__label">Back</span></button>
        <button className="icon-button" aria-label="Previous message" disabled={!canPrevious} onClick={onPrevious}><ChevronLeft size={17} /></button>
        <button className="icon-button" aria-label="Next message" disabled={!canNext} onClick={onNext}><ChevronRight size={17} /></button>
        <span className="reader-toolbar__sep" />
        <button className="icon-button" aria-label="Archive" onClick={() => dispatchAction('archive')}><Archive size={17} /></button>
        <button className="icon-button" aria-label="Delete" onClick={() => dispatchAction('trash')}><Trash2 size={17} /></button>
        <button className="icon-button" aria-label={mail.unread ? 'Mark as read' : 'Mark as unread'} aria-pressed={mail.unread} onClick={onToggleRead}><MailIcon size={17} /></button>
        <button className="icon-button" aria-label={mail.starred ? 'Unstar' : 'Star'} aria-pressed={mail.starred} onClick={onToggleStar}><Star size={17} fill={mail.starred ? 'currentColor' : 'none'} /></button>
        <button className="icon-button" aria-label="Add to calendar" onClick={onAddToCalendar} disabled={!onAddToCalendar} title="Add to calendar"><CalendarPlus size={17} /></button>
        <span className="toolbar-spacer" />
        <div className="toolbar-pop">
          <button className="icon-button" aria-label="Move to folder" aria-expanded={moveOpen} onClick={event => { event.stopPropagation(); setMoveOpen(value => !value) }} disabled={!onMove}><CornerDownRight size={17} /></button>
          {moveOpen && (
            <div className="toolbar-menu toolbar-menu--right" role="menu" aria-label="Move to folder">
              {moveChoicesAll.map(folder => (
                <button type="button" role="menuitem" key={folder} onClick={event => { event.stopPropagation(); setMoveOpen(false); onMove?.(folder) }}>{folder}</button>
              ))}
            </div>
          )}
        </div>
        <div className="toolbar-pop">
          <button className="icon-button" aria-label="Snooze" aria-expanded={snoozeOpen} onClick={event => { event.stopPropagation(); setSnoozeOpen(value => !value) }} disabled={!onSnooze}><Clock3 size={17} /></button>
          {snoozeOpen && (
            <div className="toolbar-menu toolbar-menu--right" role="menu" aria-label="Snooze until">
              {snoozeOptions.map(option => (
                <button type="button" role="menuitem" key={option.id} onClick={event => { event.stopPropagation(); setSnoozeOpen(false); onSnooze?.(snoozeAt(option.id)) }}>{option.label}</button>
              ))}
            </div>
          )}
        </div>
        <button className="icon-button" aria-label="Print" onClick={onPrint}><Printer size={17} /></button>
        <button className="icon-button" aria-label="Save email as file" onClick={() => { if (onSave) onSave(); else saveEmailAsFile(mail, thread) }}><Download size={17} /></button>
        <button className="icon-button" aria-label="Report spam" onClick={onSpam}><ShieldAlert size={17} /></button>
      </div>
      <div className="reader-content">
        <p className="eyebrow">{mail.label} · conversation</p>
        <h2>{mail.subject}</h2>
        <div className="reader-details"><span className={`avatar avatar--${mail.color}`}>{mail.initials}</span><span><strong>{mail.sender}</strong><small>&lt;{mail.email}&gt; to {recipientDisplay}</small></span><time>{mail.time}</time></div>
        <div className="thread-stack">{conversation.map((item, index) => (
          <article className={`thread-message ${openMessage === index ? 'thread-message--open' : ''}`} key={`${item.sender}-${index}`}>
            <header><span className={`avatar avatar--${item.color}`}>{item.initials}</span><span><strong>{item.sender}</strong><small>{item.email} · to {recipientDisplay}</small></span><time>{item.time}</time><button className="icon-button" aria-label={`${openMessage === index ? 'Collapse' : 'Expand'} message`} onClick={() => setOpenMessage(current => current === index ? -1 : index)}><ChevronDown size={15} /></button></header>
            {openMessage === index && <div className="reader-copy"><p>Hi Alex,</p><p>{item.copy}</p><p>Could you take a look and share your feedback?</p><p>Thanks,<br />{item.sender}</p></div>}
          </article>
        ))}</div>
        {mail.attachment && <div className="attachment"><Paperclip size={16} /><span><strong>{mail.attachmentName ?? 'attachment'}</strong><small>Scanned and safe</small></span><button className="secondary-button" onClick={downloadAttachment}><Send size={15} />Download</button></div>}
        <div className="reader-actions"><button className="primary-button" onClick={onReply}><MailIcon size={15} />Reply</button><button className="secondary-button" onClick={onReplyAll}><MailIcon size={15} />Reply all</button><button className="secondary-button" onClick={onForward}><Send size={15} />Forward</button></div>
        <button className="reply-box" onClick={onReply}><strong>Reply to {mail.sender}</strong><small>Open the composer with recipients prefilled.</small></button>
        {safeLinks && <div className="reader-links-note"><ShieldCheck size={14} /><span>Safe links are on — Harbor Mail checks the links in this message before they open.</span></div>}
      </div>
    </aside>
  )
}